

# Numpy Fuctions

Write a short introduction about Numpy and list the chosen functions. 

- np.stack
- np.vstack
- np.hstack
- np.percentile
- np.transpose


The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [83]:
%pip install jovian --upgrade -q

Note: you may need to restart the kernel to use updated packages.


In [4]:
import jovian

In [84]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "salmanrit1706114/numpy-array-operations-85d7a" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a


'https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [7]:
import numpy as np

In [9]:
# List of functions explained 
function1 = np.stack
function2 = np.vstack
function3 = np.hstack
function4 = np.percentile
function5 = np.transpose


## Function 1 - np.stack
used to join the sequence of an array along a new axis

In [27]:
'''
#AXIS =0
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5., 11.],
        [ 8.,  9.]]])
'''
arr1 = [
        [1, 2], 
        [3, 4]
        ]

arr2 = [
        [5, 11], 
        [8, 9]
        ]

np.stack((arr1, arr2),axis=1)

array([[[ 1,  2],
        [ 5, 11]],

       [[ 3,  4],
        [ 8,  9]]])

Explanation about example2: Now we will try to use stack on 2 array and we will axis eqaul to 0 axis=0

In [28]:
# Example 2 - working
arr3=[
      [1,2,3],
      [4,5,6]
     ]
arr4=[
      [7,8,9],
      [10,11,12]
     ]

In [34]:
np.stack((arr3+arr4),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Explanation about example3: It will throw error "all input arrays must have the same shape" 

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.stack((arr1, arr2), axis=0)

ValueError: all input arrays must have the same shape

Explanation about example 
(why it breaks and how to fix it)
It breaks becasue stack connect to array at certain axis and for all the axis to be matched we need same shape of array.

There is difference between concat and stack function 

In [36]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "salmanrit1706114/numpy-array-operations-85d7a" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a


'https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a'

## Function 2 - VSTACK

used to join the sequence of an array along a new axis vertically

In [37]:
# Example 1 - working
arr1 = [
        [1, 2], 
        [3, 4]
        ]

arr2 = [
        [5, 11], 
        [8, 9]
        ]


In [40]:
np.vstack((arr1,arr2))

array([[ 1,  2],
       [ 3,  4],
       [ 5, 11],
       [ 8,  9]])

try different shape along the horizontal axis

In [42]:
# Example 2 - working
arr8 = [
        [1, 2], 
        [3, 4],
        [6, 6]
        ]

arr9 = [
        [5, 11], 
        [8, 9]
        ]


In [43]:
np.vstack((arr8,arr9))

array([[ 1,  2],
       [ 3,  4],
       [ 6,  6],
       [ 5, 11],
       [ 8,  9]])

The statement breaks because while trying vstack we much have shape along vertical axis

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
arrA = [
        [1, 2,3], 
        [3, 4,3],
        ]

arrB = [
        [5, 11], 
        [8, 9]
        ]


In [46]:
np.vstack((arrA,arrB))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

the input array dimensions for the concatenation axis must match exactly,
 but along dimension 1,
  the array at index 0 has size 3 
  and the array at index 1 has size 2

  soln: change the array index at one postion

Some closing comments about when to use this function.

In [47]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "salmanrit1706114/numpy-array-operations-85d7a" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a


'https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a'

## Function 3 - HSTACK
 used to join the sequence of an array along a new axis horizontally
![image](https://i.stack.imgur.com/hSM5G.png)

In [49]:
# Example 1 - working
arr1 = [
        [1, 2], 
        [3, 4]
        ]

arr2 = [
        [5, 11], 
        [8, 9]
        ]

In [50]:
np.hstack((arr1,arr2))

array([[ 1,  2,  5, 11],
       [ 3,  4,  8,  9]])

Explanation about example

In [52]:
# Example 2 - working
arr1 = [
        [1, 2, 4], 
        [3, 4, 5]
        ]

arr2 = [
        [5, 11], 
        [8, 9]
        ]

In [53]:
np.hstack((arr1,arr2))

array([[ 1,  2,  4,  5, 11],
       [ 3,  4,  5,  8,  9]])

changed shape of array along 2 axis and it still worked

In [56]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [
        [1, 2, 4], 
        [3, 4, 5],
        [3, 4, 5]
        ]

arr2 = [
        [5, 11], 
        [8, 9]
        ]

In [57]:
np.hstack((arr1,arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

Tried with 2D array result came same

All the input array dimensions for the concatenation axis must match exactly, 
but along dimension 0, 
the array at index 0 has size 3 
and the array at index 1 has size 2

soln: use the same dimension along that axis 

Some closing comments about when to use this function.

## Function 4 - function4 = np.percentile


used to find the percentile in a NumPy array

In [66]:
# Example 1 - working
a=np.array([1,2,3,4,5,6,7,8,10])
np.percentile(a,90)
#90 percent values are below 8.4

8.4

**90 percent values are below 8.4**

In [67]:
# Example 2 - working
b=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
np.percentile(a,50)

5.0

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
b=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
np.percentile(a,110)

ValueError: Percentiles must be in the range [0, 100]

perctile range is [0,100] so error will beacuse we have given percentile 110 

soln: give Percentiles must be in the range [0, 100]

Nothig

In [70]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "salmanrit1706114/numpy-array-operations-85d7a" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a


'https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a'

## Function 5= np.transpose

used to reverse the axes of an array 

In [72]:
# Example 1 - working
a=np.array([[1,2,3],
            [4,5,6]])

np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

Explanation about example

In [74]:
# Example 2 - working
a=np.array([
            [[1,2,3],
            [4,5,6]],

            [[7,8,9],
            [10,11,12]]
             ])
np.transpose(a)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

Explanation about example

In [80]:
# Example 3 - breaking (to illustrate when it breaks)
c=np.array([[1,2,3],
            [4,5,6],
            [4,4,5]])
np.transpose(c,axis=2)

TypeError: _transpose_dispatcher() got an unexpected keyword argument 'axis'

There is no parameter like axis in transpose 

it will useful fuction


In [81]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "salmanrit1706114/numpy-array-operations-85d7a" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a


'https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Stack overflow:https://stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack

In [82]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "salmanrit1706114/numpy-array-operations-85d7a" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a


'https://jovian.ai/salmanrit1706114/numpy-array-operations-85d7a'